# Generated by Django 2.1.7 on 2019-02-18 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('name', models.CharField(max_length=140, null=True)),
                ('surname', models.CharField(max_length=140, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=140, null=True)),
                ('street_address', models.CharField(max_length=140, null=True)),
                ('city', models.CharField(max_length=140, null=True)),
                ('zip_code', models.CharField(max_length=140, null=True)),
                ('passport', models.ImageField(default='default_passport.jpg', upload_to='passports')),
                ('visa', models.ImageField(default='default_visa.jpg', upload_to='visas')),
                ('cas', models.FileField(null=True, upload_to='cas')),
                ('university_preference', models.TextField(null=True)),
                ('course_preference', models.TextField(null=True)),
                ('english_level', models.FileField(null=True, upload_to='ielts')),
                ('recent_education', models.FileField(null=True, upload_to='education')),
                ('motivation_letter', models.FileField(null=True, upload_to='motivation_letters')),
                ('cv', models.FileField(null=True, upload_to='cv')),
                ('recommendation1', models.FileField(null=True, upload_to='recommendations')),
                ('recommendation2', models.FileField(null=True, upload_to='recommendations')),
                ('recommendation3', models.FileField(null=True, upload_to='recommendations')),
                ('agreement', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
