# Generated by Django 2.1.5 on 2019-04-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promo',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
