# Generated by Django 2.1.7 on 2019-04-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_promo'),
        ('users', '0002_delete_subscriber'),
    ]

    operations = [
    ]
