# Generated by Django 2.1.7 on 2019-03-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('college_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='LinguaLogo.jpg', upload_to='college_img')),
                ('name', models.CharField(max_length=140, null=True)),
                ('coordinate_lat', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('coordinate_long', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('college_url', models.URLField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('start_date', models.CharField(blank=True, max_length=140, null=True)),
                ('type', models.CharField(max_length=140, null=True)),
                ('description', models.TextField(null=True)),
                ('attendance', models.CharField(max_length=140, null=True)),
                ('learning_mode', models.CharField(max_length=140, null=True)),
                ('student_per_class', models.IntegerField(null=True)),
                ('lesson_durations', models.IntegerField(null=True)),
                ('option1', models.CharField(blank=True, max_length=140, null=True)),
                ('original_cost1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_cost1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('option2', models.CharField(blank=True, max_length=140, null=True)),
                ('original_cost2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_cost2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('option3', models.CharField(blank=True, max_length=140, null=True)),
                ('original_cost3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_cost3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('option4', models.CharField(blank=True, max_length=140, null=True)),
                ('original_cost4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_cost4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('option5', models.CharField(blank=True, max_length=140, null=True)),
                ('original_cost5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_cost5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('housing', models.BooleanField(null=True)),
                ('housing_description', models.TextField(blank=True, null=True)),
                ('min_age', models.IntegerField(null=True)),
                ('distance', models.CharField(max_length=140, null=True)),
                ('meals', models.CharField(max_length=140, null=True)),
                ('housing_cost', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='lingua.College')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True)),
                ('picture', models.ImageField(default='default.jpg', upload_to='programme_testimonials')),
                ('comment', models.TextField(null=True)),
                ('rating', models.CharField(max_length=140, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lingua.Course')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True)),
                ('picture', models.ImageField(default='default.jpg', upload_to='programme_testimonials')),
                ('comment', models.TextField(null=True)),
                ('rating', models.CharField(max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='LinguaLogo.jpg', upload_to='university_img')),
                ('name', models.CharField(max_length=140, null=True)),
                ('coordinate_lat', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('coordinate_long', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('programme_url', models.URLField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('award', models.CharField(max_length=140, null=True)),
                ('level', models.CharField(max_length=140, null=True)),
                ('description', models.TextField(null=True)),
                ('attendance', models.CharField(max_length=140, null=True)),
                ('learning_mode', models.CharField(max_length=140, null=True)),
                ('original_cost', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('discount_cost', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True)),
                ('picture', models.ImageField(default='default.jpg', upload_to='programme_testimonials')),
                ('comment', models.TextField(null=True)),
                ('rating', models.CharField(max_length=140, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='lingua.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('university_url', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='lingua.University'),
        ),
    ]
