# Generated by Django 2.1.7 on 2019-02-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='type',
            new_name='award',
        ),
        migrations.AddField(
            model_name='programme',
            name='level',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
