# Generated by Django 2.1.7 on 2019-03-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0002_auto_20190307_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='address',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='address_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='address',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='address_link',
            field=models.URLField(null=True),
        ),
    ]
