# Generated by Django 2.1.7 on 2019-03-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0003_auto_20190307_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='discount_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
