# Generated by Django 2.1.7 on 2019-02-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0003_auto_20190224_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
