# Generated by Django 2.1.5 on 2019-03-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0004_auto_20190307_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='rating',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
