# Generated by Django 2.1.5 on 2019-03-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0005_programme_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='rating',
            new_name='ranking',
        ),
    ]
