# Generated by Django 2.1.5 on 2019-03-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0006_auto_20190316_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetestimonial',
            name='reviews_link',
        ),
        migrations.RemoveField(
            model_name='programmetestimonial',
            name='reviews_link',
        ),
        migrations.AlterField(
            model_name='programme',
            name='original_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
